name: Sync

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:        # allow manual trigger from Actions tab

jobs:
  update-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Run update script
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: node .github/scripts/updater.js

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data.json
          git commit -m "sync: update icons data list" || echo "No changes"
          git push